"""empty message

Revision ID: 132dfcd20425
Revises: ad432babb447
Create Date: 2023-01-08 11:10:32.641513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132dfcd20425'
down_revision = 'ad432babb447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views')
    # ### end Alembic commands ###
