"""empty message

Revision ID: 37c983324235
Revises: 4aeb430aef34
Create Date: 2023-01-08 10:33:50.800870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c983324235'
down_revision = '4aeb430aef34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views')
    # ### end Alembic commands ###
