"""empty message

Revision ID: ad432babb447
Revises: 37c983324235
Create Date: 2023-01-08 11:08:25.860107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad432babb447'
down_revision = '37c983324235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
